name = "jokesmith"
compatibility_date = "2024-05-05"

pages_build_output_dir = "."  # tells Cloudflare where to find static + _worker.js or /functions

# Don't add [site] or [build] in Pages projects!
